title: kleiner-brauhelfer
logo: logo.svg

search_enabled: true

plugins:
  - jekyll-seo-tag

color_scheme : dark

collections_dir: all_collections
collections:
  faqs:
    sort_by: created
    output: true
